'use strict';
const {test,before,after,beforeEach}=require('node:test'), assert=require('node:assert/strict'), bcrypt=require('bcryptjs');
process.env.NODE_ENV='test'; process.env.KK_USERNAME='policy-test'; process.env.KK_PASSWORD_HASH=bcrypt.hashSync('synthetic-password',4); process.env.KK_SESSION_SECRET='synthetic-session-only';
for (const id of ['INDRE_BY','VESTERBRO','CHRISTIANSHAVN','FISKETORVET','FREDERIKSBERG','NORREBRO']) process.env['ONLINEPOS_TOKEN_'+id]='synthetic-token';
let reads=0, provider=0, mode='normal', requested=[], readRanges=[];
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Copenhagen',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const next=d=>new Date(Date.parse(d)+86400000).toISOString().slice(0,10);
const dates=(start,end)=>{const out=[];for(let d=start;d<end;d=next(d))out.push(d);return out;};
const line={productid:'27242336',productname:'Killer Kebab',productgroupid:'1',productgroup:'Rolls',count:1,price:95,priceexclvat:76,paymenttype:'Kontant',paymenttypecode:null,date:'2026-09-20',hour:14,secondOfDay:50400};
require.cache[require.resolve('../lib/sales-read-source')]={exports:{createSalesReadSource:()=>({policy:'covered-history',async ready(){return {ready:true,source:'database'};},async read({storeSlug,start,end}){
  reads++; readRanges.push({storeSlug,start,end}); if(mode==='db-error')throw Error('PRIVATE_DATABASE_DETAIL');
  const days=dates(start,end).map(date=>({date,status:mode==='invalid'?'invalid-coverage':!mode.includes('covered')&&(date<'2026-09-20'||date>'2026-09-27'||(storeSlug==='christianshavn'&&date==='2026-09-27'))?'missing':'complete',independentlyVerified:false}));
  const complete=days.every(d=>d.status==='complete');
  return {lines:complete?days.map(d=>({...line,date:d.date})):[],meta:{source:'database',complete,storeId:storeSlug,start,end,rawLineCount:days.length,processedLineCount:days.length,coverage:{complete,days},...(complete?{}:{code:'DB_COVERAGE_INCOMPLETE'})}};
}})}};
require.cache[require.resolve('axios')]={exports:{get:async url=>{provider++; requested.push(url);if(mode.includes('provider-error'))throw Error('PRIVATE_PROVIDER_DETAIL');return {status:200,data:{current_page:1,next_page_url:null,data:dates('2026-09-19',next(today)).map((date,i)=>({orderlineid:'synthetic-'+i,productid:'27241752',productname:'',productgroupid:1,productgroup:'Drinks',count:1,price:25,priceexclvat:20,paymenttype:'Kontant',timestamp_pay:date+' 14:00:00'}))}};}}};
const app=require('../server'); let server,url,cookie;
before(async()=>{await new Promise(r=>{server=app.listen(0,'127.0.0.1',r)});url='http://127.0.0.1:'+server.address().port;const r=await fetch(url+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'policy-test',password:'synthetic-password'})});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];});
beforeEach(()=>{reads=provider=0;requested=[];readRanges=[];mode='normal';app.locals.salesRangeCache.clear();app.locals.revenueSummaryCache.clear();});
after(async()=>{app.locals.salesRangeCache.clear();app.locals.revenueSummaryCache.clear();await new Promise(r=>server.close(r));});
const get=async path=>{const response=await fetch(url+path,{headers:{Cookie:cookie}});return {status:response.status,...await response.json()};};
for(const route of ['sales-range','revenue-summary']){
 test(route+': complete historical day uses only stored data',async()=>{const r=await get('/api/'+route+'/norrebro/2026-09-20/2026-09-21');assert.equal(r.status,200);assert.equal(r.meta.source,'database');assert.equal(r.meta.readPolicy,'covered-history');assert.equal(provider,0);assert.equal(reads,1);assert.equal(route==='sales-range'?r.lines[0].priceexclvat:r.summary.completeRevenue,76);});
 test(route+': Today bypasses even a broken database',async()=>{mode='db-error';const r=await get('/api/'+route+'/norrebro/'+today+'/'+next(today));assert.equal(r.status,200);assert.equal(r.meta.source,'onlinepos');assert.equal(r.meta.routeReason,'includes-open-day');assert.equal(r.meta.databaseCoverage.checked,false);assert.equal(reads,0);assert.equal(provider,1);});
 test(route+': missing Christianshavn September 27 uses OnlinePOS for the whole day',async()=>{const r=await get('/api/'+route+'/christianshavn/2026-09-27/2026-09-28');assert.equal(r.status,200);assert.equal(r.meta.source,'onlinepos');assert.equal(r.meta.databaseCoverage.days[0].status,'missing');assert.equal(provider,1);assert.equal(route==='sales-range'?r.lines.reduce((n,l)=>n+l.priceexclvat,0):r.summary.completeRevenue,20);});
 test(route+': a covered/uncovered span never combines partial database rows',async()=>{const r=await get('/api/'+route+'/christianshavn/2026-09-26/2026-09-28');assert.equal(r.status,200);assert.equal(r.meta.source,'onlinepos');assert.deepEqual(r.meta.databaseCoverage.days.map(d=>d.status),['complete','missing']);assert.equal(r.meta.coverage.complete,true);assert.equal(provider,1);assert.equal(route==='sales-range'?r.lines.reduce((n,l)=>n+l.priceexclvat,0):r.summary.completeRevenue,40);});
 test(route+': covered history plus Today splits once at Copenhagen midnight',async()=>{mode='covered';const start=new Date(Date.parse(today)-86400000).toISOString().slice(0,10);const r=await get('/api/'+route+'/norrebro/'+start+'/'+next(today));assert.equal(r.status,200);assert.equal(r.meta.source,'hybrid');assert.equal(r.meta.complete,true);assert.deepEqual(readRanges,[{storeSlug:'norrebro',start,end:today}]);assert.equal(provider,1);assert.equal(new URL(requested[0]).pathname,'/api/exportSales/v20/'+require('../lib/pos-fetcher').cphMidnightUnix(today));assert.deepEqual(r.meta.segments.map(s=>[s.source,s.start,s.end]),[['database',start,today],['onlinepos',today,next(today)]]);assert.equal(route==='sales-range'?r.lines.reduce((n,l)=>n+l.priceexclvat,0):r.summary.completeRevenue,96);assert.equal(route==='sales-range'?r.lines.length:r.summary.dailyRevenue.length,2);});
 test(route+': hybrid provider failure discards the complete stored prefix',async()=>{mode='covered-provider-error';const start=new Date(Date.parse(today)-86400000).toISOString().slice(0,10);const r=await get('/api/'+route+'/norrebro/'+start+'/'+next(today));assert.equal(r.status,502);assert.equal(r.meta.source,'hybrid');assert.equal(r.meta.complete,false);assert.equal(r.code,'HYBRID_READ_UNAVAILABLE');assert.deepEqual(route==='sales-range'?r.lines:r.summary,route==='sales-range'?[]:null);assert.equal(provider,1);assert(!JSON.stringify(r).includes('PRIVATE_PROVIDER_DETAIL'));});
 test(route+': hybrid database failure never starts Today or falls back',async()=>{mode='db-error';const r=await get('/api/'+route+'/norrebro/2026-09-20/'+next(today));assert.equal(r.status,503);assert.equal(r.code,'DB_READ_UNAVAILABLE');assert.equal(provider,0);});
 test(route+': missing closed date plus Today fetches the original whole range',async()=>{const r=await get('/api/'+route+'/christianshavn/2026-09-26/'+next(today));assert.equal(r.status,200);assert.equal(r.meta.source,'onlinepos');assert.equal(r.meta.routeReason,'uncovered-range');assert.equal(reads,1);assert.equal(provider,1);assert.equal(new URL(requested[0]).pathname,'/api/exportSales/v20/'+require('../lib/pos-fetcher').cphMidnightUnix('2026-09-26'));});
 test(route+': database errors and invalid coverage fail visibly, with zero provider calls',async()=>{for(mode of ['db-error','invalid']){const r=await get('/api/'+route+'/norrebro/2026-09-20/2026-09-21');assert.equal(r.status,503);assert.equal(r.meta.complete,false);assert.equal(r.meta.routeReason,'database-error');assert.equal(r.meta.code,'DB_READ_UNAVAILABLE');assert(!JSON.stringify(r).includes('PRIVATE_DATABASE_DETAIL'));assert.equal(provider,0);}});
 test(route+': provider error remains a provider error with incomplete provenance',async()=>{mode='provider-error';const r=await get('/api/'+route+'/christianshavn/2026-09-27/2026-09-28');assert.equal(r.status,502);assert.equal(r.meta.source,'onlinepos');assert.equal(r.meta.complete,false);assert.equal(r.meta.databaseCoverage.complete,false);assert(!JSON.stringify(r).includes('PRIVATE_PROVIDER_DETAIL'));});
}
test('provider data keeps unresolved product warnings and source on cache hits',async()=>{for(let i=0;i<2;i++){const r=await get('/api/sales-range/indre-by/'+today+'/'+next(today));assert.equal(r.meta.source,'onlinepos');assert.deepEqual(r.meta.metrics.potentiallyIncomplete,['lemonade']);}assert.equal(provider,1);});
test('Today lemonade uses OnlinePOS and shows classification warnings; failure never becomes a partial total',async()=>{const r=await get('/api/lemonade/today');assert.equal(r.meta.source,'onlinepos');assert(r.meta.metrics.potentiallyIncomplete.includes('lemonade'));assert.equal(reads,0);assert.equal(provider,6);app.locals.salesRangeCache.clear();mode='provider-error';const bad=await get('/api/lemonade/today');assert.equal(bad.complete,false);assert.equal(bad.total,null);});
test('historical warmers do not issue redundant provider calls in coverage mode',async()=>{await app.locals.warmLyRevenueSummaries();await app.locals.warmCompletedSalesRanges();assert.equal(provider,0);});
